// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SamarPlanner.Task.Infrastructure.Persistence;

#nullable disable

namespace SamarPlanner.Task.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(TaskDbContext))]
    partial class TaskDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("task")
                .HasAnnotation("ProductVersion", "8.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SamarPlanner.Task.Core.Entities.Task", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<TimeOnly?>("DefaultTime")
                        .IsUnicode(false)
                        .HasColumnType("time");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid?>("ParentGoalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Priority")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("SoftDeleted")
                        .IsUnicode(false)
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Id", "UserId");

                    b.ToTable("Task", "task");
                });

            modelBuilder.Entity("SamarPlanner.Task.Core.Entities.TaskOccurrence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("Date")
                        .IsUnicode(false)
                        .HasColumnType("date");

                    b.Property<bool>("IsSkipped")
                        .IsUnicode(false)
                        .HasColumnType("bit");

                    b.Property<int?>("Score")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<TimeOnly?>("Time")
                        .IsUnicode(false)
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.HasIndex("TaskId");

                    b.ToTable("TaskOccurrence", "task");
                });

            modelBuilder.Entity("SamarPlanner.Task.Core.Entities.Task", b =>
                {
                    b.OwnsOne("SamarPlanner.Task.Core.Entities.RepeatPattern", "RepeatPattern", b1 =>
                        {
                            b1.Property<Guid>("TaskId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateOnly>("AnchorDate")
                                .IsUnicode(false)
                                .HasColumnType("date");

                            b1.Property<int?>("Interval")
                                .HasMaxLength(50)
                                .IsUnicode(false)
                                .HasColumnType("int");

                            b1.Property<string>("MonthDays")
                                .HasMaxLength(50)
                                .IsUnicode(false)
                                .HasColumnType("varchar(50)");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasMaxLength(50)
                                .IsUnicode(false)
                                .HasColumnType("varchar(50)");

                            b1.Property<string>("WeekDays")
                                .HasMaxLength(50)
                                .IsUnicode(false)
                                .HasColumnType("varchar(50)");

                            b1.HasKey("TaskId");

                            b1.ToTable("Task", "task");

                            b1.ToJson("RepeatPattern");

                            b1.WithOwner()
                                .HasForeignKey("TaskId");
                        });

                    b.Navigation("RepeatPattern");
                });

            modelBuilder.Entity("SamarPlanner.Task.Core.Entities.TaskOccurrence", b =>
                {
                    b.HasOne("SamarPlanner.Task.Core.Entities.Task", "Task")
                        .WithMany("Occurrences")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Task");
                });

            modelBuilder.Entity("SamarPlanner.Task.Core.Entities.Task", b =>
                {
                    b.Navigation("Occurrences");
                });
#pragma warning restore 612, 618
        }
    }
}
